### ISSUE TITLE
Point not exposed by Collage

### ISSUE THREAD

**Issue by gitLabor8** [timjs/elm-collage#2]
I'm getting below error. 
In your source file you claim to not include constructors, but I do need Point to create Paths. 

`import Collage exposing (..)
`

```
Cannot find variable `Collage.Point`.

102|          (Collage.Point (0, 0))
                 ^^^^^^^^^^^^^
`Collage` does not expose `Point`. 

```

**Comment by timjs** [comment]
Point is a type alias, it doesn't need a constructor to be created. Just use `(0,0)`.

The error points out `Point` is not a variable, that is true. Because it is a type alias you can only use it on the type level, so when giving a type to a function. I.e.:

```elm
f : Float → Collage.Point
f x = ( x, x )
```

Please familiarise yourself with basic Elm language features before opening issues for this repository. Consult the examples and the tutorial on the Elm homepage.
